version: '3.8'

services:
  vuln-research:
    build:
      context: .
      dockerfile: Dockerfile
    image: security-intelligence-framework:latest
    container_name: vuln_ml_research
    volumes:
      # Mount for live development (optional)
      - ./core:/app/core
      - ./experiments:/app/experiments
      - ./results:/app/results
    environment:
      - PYTHONHASHSEED=42
      - CUDA_LAUNCH_BLOCKING=1
      - CUBLAS_WORKSPACE_CONFIG=:4096:8
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    command: python3 smoke_test.py

  vuln-research-vertex:
    build:
      context: .
      dockerfile: Dockerfile.vertex
    image: vulnhunter-vertex:latest
    container_name: vuln_ml_research_vertex
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/cache
      - HF_HOME=/app/cache
      - TORCH_HOME=/app/cache
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
