$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json

# Job Configuration
type: command
display_name: "VulnHunter V14 Production Training"
description: "Train VulnHunter V14 on real vulnerability data using Azure ML"
experiment_name: vulnhunter-v14-production

# Code and Data
code: ./
command: python azure_vulnhunter_v14_production.py

# Compute Configuration
compute: azureml:cpu-cluster

# Environment
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest

# Outputs
outputs:
  model_output:
    mode: rw_mount
    type: uri_folder

# Tags
tags:
  version: "V14"
  purpose: "production_training"
  data_type: "real_vulnerabilities"
  model_type: "ensemble_classifier"