# VulnHunter V15 Simple Environment with Required Modules
$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: vulnhunter-v15-simple-production
version: "1"
description: Simple production environment for VulnHunter V15 with all required modules

image: mcr.microsoft.com/azureml/sklearn-1.0-ubuntu20.04-py38-cpu
conda_file: vulnhunter_v15_simple_conda.yml

tags:
  model: VulnHunter-V15
  version: "15.0.0"
  type: simple-production
  modules: "seaborn-matplotlib-sklearn"