# VulnHunter V15 PyTorch Azure ML Environment
$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: vulnhunter-v15-pytorch-production
version: "1"
description: Production PyTorch environment for VulnHunter V15 massive-scale training with 300TB+ dataset

image: mcr.microsoft.com/azureml/pytorch-1.12-ubuntu20.04-py38-cuda11.6-gpu
conda_file: vulnhunter_v15_pytorch_conda.yml

tags:
  model: VulnHunter-V15
  version: "15.0.0"
  type: pytorch-production-training
  dataset: "300TB+"
  mathematical-techniques: "8-advanced"
  enterprise-grade: "true"