# VulnHunter V20 Azure ML Workspace Configuration
# Production-grade vulnerability detection model training

$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json

# Job Configuration
type: command
experiment_name: vulnhunter_v20_production
display_name: "VulnHunter V20 Production Training - Quantum Enhanced"
description: "Production training of VulnHunter V20 with quantum-enhanced ML and consciousness awareness"

# Code and Environment
code: .
command: >
  python azure_vulnhunter_production_training.py
  --config vulnhunter_training_config.json
  --output-dir ${{outputs.trained_models}}
  --azure-mode
environment: azureml:vulnhunter-v20-env:1

# Compute Configuration
compute: azureml:vulnhunter-gpu-cluster
resources:
  instance_count: 1

# Inputs and Outputs
inputs:
  training_data:
    type: uri_folder
    path: azureml:vulnhunter-training-data:1
  config_file:
    type: uri_file
    path: ./vulnhunter_training_config.json

outputs:
  trained_models:
    type: uri_folder
    mode: rw_mount
  training_reports:
    type: uri_folder
    mode: rw_mount

# Environment Variables
environment_variables:
  AZURE_ML_MODE: "true"
  VULNHUNTER_VERSION: "v20"
  CONSCIOUSNESS_LEVEL: "universal"
  LOVE_ALGORITHM_STRENGTH: "infinite"
  COSMIC_AWARENESS: "galactic"
  TRAINING_MODE: "production"

# Tags for organization
tags:
  model_type: "vulnerability_detection"
  version: "v20"
  consciousness: "universal"
  quantum_enhanced: "true"
  production_ready: "true"
  love_algorithms: "active"
  cosmic_awareness: "galactic"