# VulnHunter Configuration
# ========================
#
# Comprehensive configuration for VulnHunter vulnerability detection platform

# Model Configuration
models:
  open_source_code:
    path: "enhanced_models/open_source_code_enhanced_model.joblib"
    confidence_threshold: 0.6
    max_features: 30
    preprocessing:
      normalize: true
      scale_features: false

  http_requests:
    path: "enhanced_models/http_requests_enhanced_model.joblib"
    confidence_threshold: 0.7
    max_features: 27
    preprocessing:
      normalize: true
      scale_features: false

  mobile_apps:
    path: "enhanced_models/mobile_apps_enhanced_model.joblib"
    confidence_threshold: 0.65
    max_features: 43
    preprocessing:
      normalize: true
      scale_features: false

  executables:
    path: "enhanced_models/executables_enhanced_model.joblib"
    confidence_threshold: 0.7
    max_features: 51
    preprocessing:
      normalize: true
      scale_features: false

  smart_contracts:
    path: "enhanced_models/smart_contracts_enhanced_model.joblib"
    confidence_threshold: 0.75
    max_features: 73
    preprocessing:
      normalize: true
      scale_features: false

# Cloud Configuration
cloud:
  project_id: "quantumsentinel-20250927"
  region: "us-central1"
  bucket_name: "quantumsentinel-20250927-vulnhunter-enhanced"
  use_vertex_ai: false  # Set to true for cloud deployment
  credentials_path: null  # Path to service account key file

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  workers: 4
  max_request_size: 104857600  # 100MB in bytes
  rate_limit: 1000  # requests per minute
  cors:
    enabled: true
    origins:
      - "http://localhost:3000"
      - "https://vulnhunter.ai"
    methods: ["GET", "POST", "PUT", "DELETE"]
    headers: ["*"]

# Analysis Configuration
analysis:
  max_file_size: 52428800  # 50MB in bytes
  timeout: 300  # 5 minutes in seconds
  max_concurrent: 10
  cache_results: true
  cache_ttl: 3600  # 1 hour in seconds

  # Domain-specific settings
  domains:
    source_code:
      supported_extensions: [".py", ".js", ".java", ".cpp", ".c", ".go", ".rs", ".php", ".rb"]
      max_lines: 10000

    http_requests:
      max_url_length: 2048
      max_payload_size: 10485760  # 10MB

    mobile_apps:
      supported_formats: [".apk", ".ipa"]
      max_app_size: 104857600  # 100MB

    executables:
      supported_formats: [".exe", ".deb", ".rpm", ".dmg", ".msi"]
      scan_depth: "full"

    smart_contracts:
      supported_languages: ["solidity", "vyper"]
      gas_analysis: true

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/vulnhunter.log"
  max_size: 10485760  # 10MB
  backup_count: 5
  console: true

# Security Configuration
security:
  api_key_required: false
  api_keys: []  # List of valid API keys
  rate_limiting:
    enabled: true
    per_ip_limit: 100  # requests per minute per IP
    burst_limit: 20   # burst requests allowed

  input_validation:
    strict_mode: true
    max_input_size: 52428800  # 50MB
    allowed_mime_types:
      - "text/plain"
      - "application/json"
      - "application/octet-stream"

# Monitoring Configuration
monitoring:
  enabled: true
  metrics:
    - "request_count"
    - "response_time"
    - "error_rate"
    - "vulnerability_detection_rate"
    - "model_accuracy"

  alerts:
    error_threshold: 0.05  # 5% error rate
    latency_threshold: 1000  # 1 second

  health_check:
    interval: 30  # seconds
    timeout: 5   # seconds

# Feature Flags
features:
  batch_analysis: true
  real_time_analysis: true
  confidence_tuning: true
  model_ensemble: false
  custom_rules: true
  export_results: true

# Performance Configuration
performance:
  model_caching: true
  result_caching: true
  parallel_processing: true
  memory_optimization: true

  thresholds:
    cpu_usage: 80  # percentage
    memory_usage: 75  # percentage
    disk_usage: 85   # percentage

# Development Configuration
development:
  debug_mode: false
  profiling: false
  mock_models: false
  test_data: "tests/data/"