version: '3.8'

services:
  vulnhunter-api:
    build:
      context: ..
      dockerfile: Dockerfile.vulnhunter
    container_name: vulnhunter-api
    ports:
      - "5000:5000"
    environment:
      - VULNHUNTER_HOST=0.0.0.0
      - VULNHUNTER_PORT=5000
      - VULNHUNTER_DEBUG=False
      - VULNHUNTER_LOG_LEVEL=INFO
      - VULNHUNTER_REQUIRE_AUTH=True
      - VULNHUNTER_API_KEY=${VULNHUNTER_API_KEY:-monitoring-demo-key}
    volumes:
      - ../logs:/app/logs
      - ../models:/app/models
    restart: unless-stopped
    networks:
      - vulnhunter-monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml
      - ./vulnhunter_rules.yml:/etc/prometheus/vulnhunter_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - vulnhunter-monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana_dashboard.json:/etc/grafana/provisioning/dashboards/vulnhunter.json
      - ./grafana_provisioning.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=vulnhunter123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: unless-stopped
    networks:
      - vulnhunter-monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager_config.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    restart: unless-stopped
    networks:
      - vulnhunter-monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - vulnhunter-monitoring

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

networks:
  vulnhunter-monitoring:
    driver: bridge