# Prometheus Configuration for VulnHunter Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "vulnhunter_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'vulnhunter-api'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']