name: vulnhunter-v10
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyterlab
  - pip
  - pip:
    - torch>=2.0.0
    - torchvision>=0.15.0
    - transformers>=4.20.0
    - datasets>=2.0.0
    - accelerate>=0.20.0
    - wandb>=0.15.0
    - mlflow>=2.0.0
    - azureml-sdk>=1.50.0
    - networkx>=2.8.0
    - gudhi>=3.6.0  # For topological data analysis
    - pennylane>=0.30.0  # For quantum-inspired components
    - scipy>=1.9.0
    - tqdm>=4.64.0
    - requests>=2.28.0