# VulnHunter Î© Kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnhunter-omega
  namespace: security
  labels:
    app: vulnhunter-omega
    version: v2.0
    component: analysis-engine
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: vulnhunter-omega
  template:
    metadata:
      labels:
        app: vulnhunter-omega
        version: v2.0
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: vulnhunter-omega
        image: vulnhunter/omega:v2.0
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8765
          name: websocket
          protocol: TCP
        env:
        - name: VULNHUNTER_ENV
          value: "production"
        - name: VULNHUNTER_LOG_LEVEL
          value: "INFO"
        - name: VULNHUNTER_MAX_WORKERS
          value: "4"
        - name: VULNHUNTER_ENABLE_REALTIME
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "8Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: models-cache
          mountPath: /app/models
          readOnly: true
        - name: temp-storage
          mountPath: /tmp
      volumes:
      - name: models-cache
        configMap:
          name: vulnhunter-models
      - name: temp-storage
        emptyDir:
          sizeLimit: 1Gi
      nodeSelector:
        node-type: compute-optimized
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "security"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: vulnhunter-omega-service
  namespace: security
  labels:
    app: vulnhunter-omega
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8765
    targetPort: 8765
    protocol: TCP
    name: websocket
  selector:
    app: vulnhunter-omega

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vulnhunter-omega-ingress
  namespace: security
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: vulnhunter-omega-service
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - vulnhunter.security.domain.com
    secretName: vulnhunter-tls
  rules:
  - host: vulnhunter.security.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vulnhunter-omega-service
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vulnhunter-omega-hpa
  namespace: security
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vulnhunter-omega
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30