$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: python azure_train.py
code: ./azure_training_package
environment: azureml://registries/azureml/environments/sklearn-1.0/labels/latest
compute: vulnhunter-payg-cluster
experiment_name: vulnhunter_v5_azure_training
display_name: VulnHunter V5 Azure Training Fixed
description: VulnHunter V5 training with proper file packaging
