$schema: https://azuremlschemas.azureedge.net/latest/amlCompute.schema.json
name: vulnhunter-cpu-cluster
type: amlcompute
size: Standard_DS3_v2
location: eastus2
min_instances: 0
max_instances: 4
idle_time_before_scale_down: 300
description: CPU cluster for VulnHunter V5 training