$schema: https://azuremlschemas.azureedge.net/latest/amlCompute.schema.json
name: vulnhunter-gpu-cluster
type: amlcompute
size: Standard_NC6s_v3
location: eastus2
min_instances: 0
max_instances: 4
idle_time_before_scale_down: 300
description: GPU cluster for VulnHunter V5 training