$schema: https://azuremlschemas.azureedge.net/latest/workspace.schema.json
name: vulnhunter-v5-cpu-workspace
location: eastus2
resource_group: vulnhunter-v5-cpu-rg
description: VulnHunter V5 CPU-Optimized ML Workspace for large-scale training
storage_account: /subscriptions/65dfba04-0285-4864-85b2-b9b8c211b62e/resourceGroups/vulnhunter-v5-cpu-rg/providers/Microsoft.Storage/storageAccounts/vulnhunterv5cpustorage
key_vault: /subscriptions/65dfba04-0285-4864-85b2-b9b8c211b62e/resourceGroups/vulnhunter-v5-cpu-rg/providers/Microsoft.KeyVault/vaults/vulnhunter-v5-cpu-kv
application_insights: /subscriptions/65dfba04-0285-4864-85b2-b9b8c211b62e/resourceGroups/vulnhunter-v5-cpu-rg/providers/Microsoft.Insights/components/vulnhuntinsights92958407
tags:
  project: vulnhunter-v5-cpu
  purpose: cpu-optimized-training
  version: "5.0"