$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: vulnhunter-v5-env
description: VulnHunter V5 training environment
conda_file: conda_env.yml
image: mcr.microsoft.com/azureml/pytorch-1.13-ubuntu20.04-py38-cuda11.6-gpu:latest