$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: python simple_ml_train.py --data-path ./real_vulnhunter_v5_dataset.csv --output-dir ./outputs
code: ./azure_training
inputs: {}
outputs:
  model_output:
    type: uri_folder
environment: azureml:vulnhunter-v5-env:1
compute: vulnhunter-cpu-cluster
experiment_name: vulnhunter-v5-final-training
description: VulnHunter V5 final training with sklearn RandomForest