$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: >-
  python azure_train.py
inputs:
  training_data:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/azure_training_package/production_full
outputs:
  model_output:
    type: uri_folder
    mode: rw_mount
environment: azureml://registries/azureml/environments/sklearn-1.0/labels/latest
compute: vulnhunter-payg-cluster
experiment_name: vulnhunter_v5_full_dataset
display_name: VulnHunter V5 Full Dataset Training (188K samples)
description: VulnHunter V5 training with full 188K sample dataset via AzCopy upload
tags:
  project: vulnhunter-v5
  purpose: full-dataset-training
  samples: "188672"
  upload_method: azcopy
code: azureml://datastores/workspaceblobstore/paths/azure_training_package
