$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: python azure_train_full188k.py
code: ./azure_fixed_training
inputs:
  training_data:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/azure_training_package/azure_training_package/production_full
outputs:
  model_output:
    type: uri_folder
    mode: rw_mount
environment: azureml://registries/azureml/environments/sklearn-1.0/labels/latest
compute: vulnhunter-payg-cluster
experiment_name: vulnhunter_v5_full_188k
display_name: VulnHunter V5 FULL 188K Dataset Training
description: VulnHunter V5 training with complete 188,672 sample dataset - NO SAMPLING
tags:
  project: vulnhunter-v5
  purpose: full-188k-dataset
  samples: "188672"
  dataset_size: "340MB"
  sampling: "none"
  target: "full-dataset"
