$schema: https://azuremlschemas.azureedge.net/latest/amlCompute.schema.json
name: vulnhunter-gpu-ncasv3-t4
type: amlcompute
size: Standard_NC4as_T4_v3
location: eastus2
min_instances: 0
max_instances: 4
idle_time_before_scale_down: 300
description: VulnHunter V5 GPU cluster with NCASv3_T4 dedicated vCPUs for enhanced deep learning training
tier: dedicated