$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: python train_ncasv3_style.py --dataset-size 40000 --target-f1 0.98 --output-dir ./outputs
code: .
inputs: {}
outputs:
  model_output:
    type: uri_folder
environment: azureml://registries/azureml/environments/sklearn-1.0/versions/5
compute: vulnhunter-enhanced-cluster
experiment_name: vulnhunter-v5-ncasv3-style
description: VulnHunter V5 NCASv3_T4-style training with dedicated vCPUs, 40K samples, F1 target 0.98