$schema: https://azuremlschemas.azureedge.net/latest/workspace.schema.json
name: vulnhunter-v5-payg-workspace
location: eastus2
resource_group: vulnhunter-v5-payg-rg
description: VulnHunter V5 Pay-As-You-Go ML Workspace for smart contract analysis
storage_account: /subscriptions/65dfba04-0285-4864-85b2-b9b8c211b62e/resourceGroups/vulnhunter-v5-payg-rg/providers/Microsoft.Storage/storageAccounts/vulnhunterv5paygstorage
key_vault: /subscriptions/65dfba04-0285-4864-85b2-b9b8c211b62e/resourceGroups/vulnhunter-v5-payg-rg/providers/Microsoft.KeyVault/vaults/vulnhunter-v5-payg-kv
tags:
  project: vulnhunter-v5-payg
  purpose: smart-contract-analysis
  pricing: pay-as-you-go
  version: "5.0"
