$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: python azure_train_fixed.py
code: ./azure_fixed_training
inputs:
  training_data:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/azure_training_package/azure_training_package/production_full
outputs:
  model_output:
    type: uri_folder
    mode: rw_mount
environment: azureml://registries/azureml/environments/sklearn-1.0/labels/latest
compute: vulnhunter-payg-cluster
experiment_name: vulnhunter_v5_production_full
display_name: VulnHunter V5 Production Full Dataset Training (188K)
description: VulnHunter V5 training with full 188K dataset - Fixed dataset access
tags:
  project: vulnhunter-v5
  purpose: production-full-dataset
  samples: "188672"
  dataset_size: "340MB"
  version: "fixed"
