$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: python azure_train_vulnhunter_v6.py
code: ./azure_fixed_training
inputs:
  training_data:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/azure_training_package/azure_training_package/production_full
outputs:
  model_output:
    type: uri_folder
    mode: rw_mount
environment: azureml://registries/azureml/environments/sklearn-1.0/labels/latest
compute: vulnhunter-payg-cluster
experiment_name: vulnhunter_v6_mathematical_research_fixed
display_name: VulnHunter V6 Mathematical Research - Fixed Dependencies
description: |
  VulnHunter V6 Research Training with Novel Mathematical Features (Fixed):
  - Algebraic Topology (Betti numbers, Euler characteristic, Homology)
  - Information Theory (Shannon entropy, Kolmogorov complexity, Mutual information)
  - Differential Geometry (Curvature analysis, Manifold modeling)
  - Formal Verification (Temporal logic, Invariant checking)
  - Graph Theory (Spectral analysis, Connectivity measures)
  - Advanced Ensemble Learning (RF, GradientBoost, AdaBoost, Neural Networks)

  Fixed: Replaced XGBoost/LightGBM with sklearn-native alternatives
  Target: 188,672 samples with 186+ mathematical features for research paper
tags:
  project: vulnhunter-v6-research-fixed
  purpose: mathematical-enhancement-fixed
  samples: "188672"
  features: "186+"
  research: "novel-mathematical-methods"
  paper: "formal-verification-topology"
  methods: "algebraic-topology,information-theory,differential-geometry"
  verification: "temporal-logic,formal-methods"
  ensemble: "sklearn-native"
  innovation: "topological-security-analysis"
  status: "dependency-fixed"