# Advanced Vulnerability Detection Model Configuration
model:
  # Base model configuration
  code_bert_model: "microsoft/codebert-base"
  hidden_size: 768
  num_classes: 30  # Updated for expanded vulnerability types
  learning_rate: 0.00002
  batch_size: 8
  epochs: 15  # Increased for more complex model
  max_sequence_length: 512  # Increased for better context

  # Advanced architecture parameters
  d_model: 512
  num_layers: 6
  num_heads: 8
  ff_dim: 2048
  dropout: 0.1

  # Ensemble configuration
  ensemble_models: 4
  uncertainty_samples: 10
  distillation_temperature: 4.0
  distillation_alpha: 0.7

data:
  supported_languages: ["python", "java", "c", "cpp", "javascript", "go", "php", "c#", "rust", "kotlin"]
  train_test_split: 0.8
  validation_split: 0.2

  # Dataset expansion
  min_samples_per_class: 100
  max_samples_per_class: 10000
  augmentation_factor: 2.0
  synthetic_data_ratio: 0.3

training:
  early_stopping_patience: 8  # Increased patience
  save_best_only: true
  log_interval: 10

  # Advanced training techniques
  gradient_clipping: 1.0
  weight_decay: 0.01
  scheduler: "cosine_annealing"
  warmup_steps: 1000

  # Multi-task learning weights
  task_weights:
    vulnerability_detection: 1.0
    type_classification: 0.8
    severity_regression: 0.6
    exploitability_classification: 0.4
    confidence_estimation: 0.3

evaluation:
  metrics: ["accuracy", "precision", "recall", "f1", "auc_roc", "auc_pr"]
  cross_validation_folds: 5
  statistical_significance_test: true
  confidence_intervals: true

# Comprehensive Vulnerability Types (30 classes)
vulnerability_types:
  # Injection Vulnerabilities
  - "sql_injection"              # ID: 0  - SQL injection attacks
  - "nosql_injection"            # ID: 1  - NoSQL injection attacks
  - "command_injection"          # ID: 2  - OS command injection
  - "ldap_injection"             # ID: 3  - LDAP injection
  - "xpath_injection"            # ID: 4  - XPath injection

  # Cross-Site Scripting (XSS)
  - "reflected_xss"              # ID: 5  - Reflected XSS
  - "stored_xss"                 # ID: 6  - Stored/Persistent XSS
  - "dom_xss"                    # ID: 7  - DOM-based XSS

  # Authentication & Session Management
  - "broken_authentication"      # ID: 8  - Broken authentication mechanisms
  - "session_fixation"           # ID: 9  - Session fixation attacks
  - "weak_password_recovery"     # ID: 10 - Weak password recovery

  # Authorization & Access Control
  - "idor"                       # ID: 11 - Insecure Direct Object References
  - "privilege_escalation"       # ID: 12 - Privilege escalation
  - "path_traversal"             # ID: 13 - Path/Directory traversal

  # Cryptographic Failures
  - "weak_cryptography"          # ID: 14 - Weak cryptographic algorithms
  - "hardcoded_credentials"      # ID: 15 - Hardcoded passwords/keys
  - "insufficient_entropy"       # ID: 16 - Insufficient entropy in random generation

  # Memory Safety (C/C++)
  - "buffer_overflow"            # ID: 17 - Buffer overflow
  - "integer_overflow"           # ID: 18 - Integer overflow
  - "format_string"              # ID: 19 - Format string vulnerability

  # Advanced Injection Types
  - "insecure_deserialization"   # ID: 20 - Insecure deserialization
  - "xxe"                        # ID: 21 - XML External Entity (XXE)

  # Configuration & Design Issues
  - "security_misconfiguration"  # ID: 22 - Security misconfiguration
  - "csrf"                       # ID: 23 - Cross-Site Request Forgery
  - "race_condition"             # ID: 24 - Race condition vulnerability

  # Modern Attack Vectors
  - "ssrf"                       # ID: 25 - Server-Side Request Forgery
  - "business_logic_flaw"        # ID: 26 - Business logic vulnerabilities
  - "api_security_flaw"          # ID: 27 - API security issues
  - "supply_chain_attack"        # ID: 28 - Supply chain attacks

  # No Vulnerability
  - "none"                       # ID: 29 - No vulnerability detected

# Vulnerability Categories for Hierarchical Classification
vulnerability_categories:
  injection: [0, 1, 2, 3, 4, 5, 6, 7, 20, 21, 25]
  authentication: [8, 9, 10, 23]
  authorization: [11, 12, 13]
  cryptographic: [14, 15, 16]
  memory_safety: [17, 18, 19]
  configuration: [22, 29]
  business_logic: [24, 26]
  api_security: [27]
  supply_chain: [28]

# OWASP Top 10 2021 Mapping
owasp_mapping:
  "A01:2021 - Broken Access Control": [11, 12, 13, 23, 27]
  "A02:2021 - Cryptographic Failures": [14, 15, 16]
  "A03:2021 - Injection": [0, 1, 2, 3, 4, 5, 6, 7]
  "A04:2021 - Insecure Design": [24, 26]
  "A05:2021 - Security Misconfiguration": [21, 22]
  "A06:2021 - Vulnerable Components": [17, 18, 19, 28]
  "A07:2021 - Identification and Authentication Failures": [8, 9, 10]
  "A08:2021 - Software and Data Integrity Failures": [20]
  "A09:2021 - Security Logging and Monitoring Failures": []
  "A10:2021 - Server-Side Request Forgery": [25]

# Severity Mapping (for CVSS-based training)
severity_mapping:
  critical: [0, 2, 12, 15, 17, 20, 28]      # CVSS 9.0-10.0
  high: [1, 6, 8, 11, 13, 14, 19, 21, 25, 27]  # CVSS 7.0-8.9
  medium: [4, 5, 7, 9, 10, 16, 18, 22, 23, 24, 26]  # CVSS 4.0-6.9
  low: [3]                                   # CVSS 0.1-3.9
  none: [29]                                 # CVSS 0.0

# Advanced Features
features:
  graph_analysis: true
  attention_visualization: true
  uncertainty_quantification: true
  explainable_ai: true
  adversarial_robustness: true

  # Model architectures to use
  architectures:
    - "multi_scale_transformer"
    - "graph_neural_network"
    - "ensemble_models"
    - "knowledge_distillation"

# Visualization Configuration
visualization:
  attention_heatmaps: true
  feature_importance: true
  confusion_matrix: true
  roc_curves: true
  precision_recall_curves: true
  tsne_clustering: true

# Export Configuration
export:
  model_format: ["pytorch", "onnx", "tensorrt"]
  include_metadata: true
  include_explanations: true
