apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vulnhunter-api-hpa
  namespace: vulnhunter
  labels:
    app: vulnhunter
    component: hpa-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vulnhunter-api
  minReplicas: 5
  maxReplicas: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 5
        periodSeconds: 60
      selectPolicy: Max

  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

  # Custom metric: API response time
  - type: Pods
    pods:
      metric:
        name: vulnhunter_api_response_time_ms
      target:
        type: AverageValue
        averageValue: "10"

  # Custom metric: Queue length
  - type: Pods
    pods:
      metric:
        name: vulnhunter_analysis_queue_length
      target:
        type: AverageValue
        averageValue: "10"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vulnhunter-worker-hpa
  namespace: vulnhunter
  labels:
    app: vulnhunter
    component: hpa-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vulnhunter-worker
  minReplicas: 10
  maxReplicas: 100
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 30
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 200
        periodSeconds: 30
      - type: Pods
        value: 10
        periodSeconds: 30
      selectPolicy: Max

  metrics:
  # CPU utilization (workers are CPU intensive)
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75

  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85

  # Custom metric: Jobs per second
  - type: Pods
    pods:
      metric:
        name: vulnhunter_jobs_per_second
      target:
        type: AverageValue
        averageValue: "5"

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vulnhunter-api-pdb
  namespace: vulnhunter
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: vulnhunter
      component: api

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vulnhunter-worker-pdb
  namespace: vulnhunter
spec:
  minAvailable: 5
  selector:
    matchLabels:
      app: vulnhunter
      component: worker